### ISSUE TITLE
Empty text field validation:

### ISSUE THREAD

**Issue by Bibek2207303** [Rohan2204755/BakeryManagementSystem#17]
Empty text field validation while adding employee. Please fix the bug asap.

**Comment by Rohan2204755** [comment]
I have sloved this bug by using joptionpane.showmessagedialog. When the user tries to add employee without filling all forms the application throws the message "You cannot  leave textfield empty"

**Comment by Bibek2207303** [comment]
Ok. I have now tested the system. Works perfectly now. Thankyou.
